### ISSUE TITLE
Ability to filter according to specific collections

### ISSUE THREAD

**Issue by fourg6x** [lagenar/shopify-scraper#2]
I am experiencing connection issues intermittently as Shopify bans IPs that are making too many requests.  I'm failing to extract all products.  The only solution I see is either proxy-switching or modify the script to extract data in smaller chunks according to specific Collection(s) products belong to.

Perhaps at the top of the script set an option to pull only from a set array of collections, ie:
[ 'Collection 1', 'Collection 2' ]

Products that are not under these collections would be ignored.

**Comment by lagenar** [comment]
Hi there, thanks for the suggestion. I think it's a good idea to add it. I'll look at the best way to implement this feature.

**Comment by lagenar** [comment]
This has been added. Now there's an option called --list-collections that outputs all the collections in the site and also an option -c that can receive a list of collections to scrape. This is documented in the readme.
